return {
 ["Fira Mono Bold#655360"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Bold.otf", false },
 ["Fira Mono#655360"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Regular.otf", false },
 ["Fira Sans Italic#655360"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Italic.otf", false },
 ["Fira Sans Light Italic#655360"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-LightItalic.otf", false },
 ["Fira Sans Light#655360"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["Fira Sans#655360"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Book.otf", false },
 ["FiraMono/BI:mode=node;script=latn;language=dflt;#bi#717620"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-BoldOblique.otf", false },
 ["FiraMono/BI:mode=node;script=latn;language=dflt;#bi#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-BoldOblique.otf", false },
 ["FiraMono/I:mode=node;script=latn;language=dflt;#i#717620"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Oblique.otf", false },
 ["FiraMono/I:mode=node;script=latn;language=dflt;#i#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Oblique.otf", false },
 ["FiraMono:mode=node;#717617"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Regular.otf", false },
 ["FiraMono:mode=node;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Regular.otf", false },
 ["FiraMono:mode=node;script=latn;language=dflt;#717619"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Regular.otf", false },
 ["FiraMono:mode=node;script=latn;language=dflt;#717620"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Regular.otf", false },
 ["FiraMono:mode=node;script=latn;language=dflt;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Regular.otf", false },
 ["FiraMonoMedium/I:mode=node;script=latn;language=dflt;#i#717620"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Medium.otf", false },
 ["FiraMonoMedium:mode=node;script=latn;language=dflt;#717620"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Medium.otf", false },
 ["FiraMonoMedium:mode=node;script=latn;language=dflt;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraMono-Medium.otf", false },
 ["FiraSans:mode=node;script=latn;language=dflt;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Book.otf", false },
 ["FiraSans:mode=node;script=latn;language=dflt;+tlig;#655360"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Book.otf", false },
 ["FiraSans:mode=node;script=latn;language=dflt;+tlig;#717619"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Book.otf", false },
 ["FiraSans:mode=node;script=latn;language=dflt;+tlig;+smcp;#786432"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Book.otf", false },
 ["FiraSans:mode=node;script=latn;language=dflt;+tlig;+smcp;#943718"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Book.otf", false },
 ["FiraSansItalic:mode=node;script=latn;language=dflt;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Italic.otf", false },
 ["FiraSansLight:mode=node;#717617"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;script=latn;language=dflt;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;script=latn;language=dflt;+tlig;#262144"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;script=latn;language=dflt;+tlig;#327680"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;script=latn;language=dflt;+tlig;#393216"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;script=latn;language=dflt;+tlig;#458752"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;script=latn;language=dflt;+tlig;#524288"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;script=latn;language=dflt;+tlig;#655360"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;script=latn;language=dflt;+tlig;#717619"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;script=latn;language=dflt;+tlig;#786432"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;script=latn;language=dflt;+tlig;#943718"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;script=latn;language=dflt;+tlig;+smcp;#786432"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLight:mode=node;script=latn;language=dflt;+tlig;+smcp;#943718"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-Light.otf", false },
 ["FiraSansLightItalic:mode=node;script=latn;language=dflt;#717621"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-LightItalic.otf", false },
 ["FiraSansLightItalic:mode=node;script=latn;language=dflt;+tlig;#327680"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-LightItalic.otf", false },
 ["FiraSansLightItalic:mode=node;script=latn;language=dflt;+tlig;#393216"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-LightItalic.otf", false },
 ["FiraSansLightItalic:mode=node;script=latn;language=dflt;+tlig;#458752"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-LightItalic.otf", false },
 ["FiraSansLightItalic:mode=node;script=latn;language=dflt;+tlig;#524288"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-LightItalic.otf", false },
 ["FiraSansLightItalic:mode=node;script=latn;language=dflt;+tlig;#655360"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-LightItalic.otf", false },
 ["FiraSansLightItalic:mode=node;script=latn;language=dflt;+tlig;#717619"]={ "/usr/share/texlive/texmf-dist/fonts/opentype/public/fira/FiraSans-LightItalic.otf", false },
 ["TeXGyreCursor/B:mode=node;script=latn;language=dflt;#b#717620"]={ "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyrecursor-bold.otf", false },
 ["TeXGyreCursor/B:mode=node;script=latn;language=dflt;#b#717621"]={ "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyrecursor-bold.otf", false },
 ["TeXGyreCursor/BI:mode=node;script=latn;language=dflt;#bi#717620"]={ "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyrecursor-bolditalic.otf", false },
 ["TeXGyreCursor/BI:mode=node;script=latn;language=dflt;#bi#717621"]={ "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyrecursor-bolditalic.otf", false },
 ["TeXGyreCursor/I:mode=node;script=latn;language=dflt;#i#717620"]={ "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyrecursor-italic.otf", false },
 ["TeXGyreCursor/I:mode=node;script=latn;language=dflt;#i#717621"]={ "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyrecursor-italic.otf", false },
 ["TeXGyreCursor:mode=node;#717617"]={ "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyrecursor-regular.otf", false },
 ["TeXGyreCursor:mode=node;#717621"]={ "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyrecursor-regular.otf", false },
 ["TeXGyreCursor:mode=node;script=latn;language=dflt;#717620"]={ "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyrecursor-regular.otf", false },
 ["TeXGyreCursor:mode=node;script=latn;language=dflt;#717621"]={ "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyrecursor-regular.otf", false },
 ["TeXGyreHeros/B:mode=node;script=latn;language=dflt;#b#717620"]={ "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyreheros-bold.otf", false },
 ["TeXGyreHeros/B:mode=node;script=latn;language=dflt;#b#717621"]={ "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyreheros-bold.otf", false },
 ["TeXGyreHeros/BI:mode=node;script=latn;language=dflt;#bi#717620"]={ "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyreheros-bolditalic.otf", false },
 ["TeXGyreHeros/BI:mode=node;script=latn;language=dflt;#bi#717621"]={ "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyreheros-bolditalic.otf", false },
 ["TeXGyreHeros/I:mode=node;script=latn;language=dflt;#i#717620"]={ "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyreheros-italic.otf", false },
 ["TeXGyreHeros/I:mode=node;script=latn;language=dflt;#i#717621"]={ "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyreheros-italic.otf", false },
 ["TeXGyreHeros:mode=node;#717617"]={ "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyreheros-regular.otf", false },
 ["TeXGyreHeros:mode=node;#717621"]={ "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyreheros-regular.otf", false },
 ["TeXGyreHeros:mode=node;script=latn;language=dflt;#717620"]={ "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyreheros-regular.otf", false },
 ["TeXGyreHeros:mode=node;script=latn;language=dflt;#717621"]={ "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyreheros-regular.otf", false },
 ["TeXGyreHeros:mode=node;script=latn;language=dflt;+tlig;#717619"]={ "/usr/share/texmf/fonts/opentype/public/tex-gyre/texgyreheros-regular.otf", false },
}
