image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [495.97306,   0.     , 318.26219,
           0.     , 496.74468, 212.37086,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.091854, -0.146431, -0.004546, 0.002610, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [502.02921,   0.     , 319.37477,   0.     ,
           0.     , 503.06381, 210.04677,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
